AWSTemplateFormatVersion: "2010-09-09"
Description: "VPN Gateway Template for Site-to-Site VPN"

Parameters:
  VPCId:
    Type: String
    Description: "The VPC ID to which the VGW will attach"

  SubnetId:
    Type: String
    Description: "The subnet ID to which the route table will attach"

  VPCEndpointSSMId:
    Type: String
    Description: "The ID of the VPC Endpoint for SSM"

  VPCEndpointSSMMessagesID:
    Type: String
    Description: "The ID of the VPC Endpoint for SSM Messages"

  VPCEndpointEC2MessagesID:
    Type: String
    Description: "The ID of the VPC Endpoint for EC2 Messages"

  CustomerGatewayIP:
    Type: String
    Description: "The IP address of the Customer Gateway (Azure VPN Gateway)"
    Default: "1.1.1.1"

  PrivateSubnetCIDR:
    Type: String
    Description: "The CIDR block of the private subnet where the EC2 instance resides"
    Default: "192.168.1.0/24"

  Environment:
    Type: String
    Description: The environment name (e.g., development, production)
    AllowedValues:
      - development
      - production
      - default

Resources:
  # Create a VPN Gateway (VGW)
  VGW:
    Type: AWS::EC2::VPNGateway
    Properties:
      Type: "ipsec.1"
      AmazonSideAsn: 65001
      Tags:
        - Key: Name
          Value: !Sub 'VGW_${Environment}'

  # Attach VGW to VPC
  VGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPCId
      VpnGatewayId: !Ref VGW

Outputs:
  VGWId:
    Description: "The ID of the created VPN Gateway"
    Value: !Ref VGW